/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ksir_penjualan;

import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class ksir_penjualan extends javax.swing.JFrame {
int a,b,h;
    /**
     * Creates new form ksir_penjualan
     */
    public ksir_penjualan() {
        initComponents();
        int bayar;
    }
    private void tanggal(){
         java.util.Date sekarang = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat ("dd-MM-yyyy") ;
        lbl_tanggal.setText("Tanggal "+kal.format(sekarang));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nasgor = new javax.swing.JRadioButton();
        migor = new javax.swing.JRadioButton();
        soyam = new javax.swing.JRadioButton();
        sokam = new javax.swing.JRadioButton();
        Nasi = new javax.swing.JRadioButton();
        txt_nasgor = new javax.swing.JTextField();
        txt_migor = new javax.swing.JTextField();
        txt_soyam = new javax.swing.JTextField();
        txt_sokam = new javax.swing.JTextField();
        txt_nasi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_ng = new javax.swing.JTextField();
        txt_soto = new javax.swing.JTextField();
        txt_mg = new javax.swing.JTextField();
        txt_sop_kmbg = new javax.swing.JTextField();
        txt_rice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_harga = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        caramel = new javax.swing.JRadioButton();
        cafemocha = new javax.swing.JRadioButton();
        capucino = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        vanilalatte = new javax.swing.JRadioButton();
        americano = new javax.swing.JRadioButton();
        txt_crmel_late = new javax.swing.JTextField();
        txt_capucino = new javax.swing.JTextField();
        txt_cfe_mcha = new javax.swing.JTextField();
        txt_vnla_late = new javax.swing.JTextField();
        txt_amrcano = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_crml = new javax.swing.JTextField();
        txt_cpn = new javax.swing.JTextField();
        txt_mocha = new javax.swing.JTextField();
        txt_vanila_latte = new javax.swing.JTextField();
        txt_americano = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Totalharga = new javax.swing.JLabel();
        Totalharga1 = new javax.swing.JLabel();
        Totalharga2 = new javax.swing.JLabel();
        lbl_tanggal = new javax.swing.JLabel();
        txt_bayar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_kembalian = new javax.swing.JTextField();
        btn_kembalian = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ksir Caffe");

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Splash", 0, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("KASIR CAFE ");

        nasgor.setText("Nasi Goreng");
        nasgor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nasgorActionPerformed(evt);
            }
        });

        migor.setText("Mie Goreng");
        migor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                migorActionPerformed(evt);
            }
        });

        soyam.setText("Soto Ayam");
        soyam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soyamActionPerformed(evt);
            }
        });

        sokam.setText("Sop Kambing");
        sokam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sokamActionPerformed(evt);
            }
        });

        Nasi.setText("Nasi");
        Nasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NasiActionPerformed(evt);
            }
        });

        txt_soyam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_soyamActionPerformed(evt);
            }
        });

        jLabel2.setText("Pesan");

        txt_ng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ngActionPerformed(evt);
            }
        });

        txt_sop_kmbg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sop_kmbgActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tarzan", 0, 13)); // NOI18N
        jLabel3.setText("Jumlah Harga");

        txt_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hargaActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 153));
        jButton1.setText("Hitung");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 153));
        jButton2.setText("Hapus");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 153));
        jButton3.setText("Keluar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        caramel.setText("Caramel Latte");
        caramel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caramelActionPerformed(evt);
            }
        });

        cafemocha.setText("Cafe Mocha");
        cafemocha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cafemochaActionPerformed(evt);
            }
        });

        capucino.setText("Cappucino");
        capucino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capucinoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Viner Hand ITC", 0, 15)); // NOI18N
        jLabel5.setText("Menu Makanan");

        vanilalatte.setText("Vanilla latte");
        vanilalatte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vanilalatteActionPerformed(evt);
            }
        });

        americano.setText("Americano");
        americano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                americanoActionPerformed(evt);
            }
        });

        jLabel6.setText("Pesan");

        txt_crml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_crmlActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Viner Hand ITC", 0, 15)); // NOI18N
        jLabel7.setText("Menu Minuman");

        Totalharga.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Totalharga.setForeground(new java.awt.Color(51, 0, 51));
        Totalharga.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Totalharga.setText("Struct");
        Totalharga.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Totalharga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TotalhargaMouseClicked(evt);
            }
        });

        Totalharga1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Totalharga1.setForeground(new java.awt.Color(51, 0, 51));
        Totalharga1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Totalharga1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Totalharga1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Totalharga1MouseClicked(evt);
            }
        });

        Totalharga2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Totalharga2.setForeground(new java.awt.Color(51, 0, 51));
        Totalharga2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Totalharga2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Totalharga2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Totalharga2MouseClicked(evt);
            }
        });

        lbl_tanggal.setText("Tanggal");

        txt_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bayarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tarzan", 0, 13)); // NOI18N
        jLabel4.setText("Bayar");

        txt_kembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kembalianActionPerformed(evt);
            }
        });

        btn_kembalian.setBackground(new java.awt.Color(0, 0, 153));
        btn_kembalian.setText("Kembalian");
        btn_kembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembalianActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Nasi)
                                .addGap(265, 265, 265))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nasgor)
                                            .addComponent(migor))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_nasgor)
                                            .addComponent(txt_migor)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(sokam)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(soyam)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_sokam, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                            .addComponent(txt_nasi)
                                            .addComponent(txt_harga)
                                            .addComponent(txt_soyam, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addGap(7, 7, 7))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_soto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_mg, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_sop_kmbg, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_rice, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(americano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(vanilalatte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(capucino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cafemocha, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_capucino, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                    .addComponent(txt_cfe_mcha)
                                    .addComponent(txt_vnla_late)
                                    .addComponent(txt_amrcano)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_ng, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(caramel)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_crmel_late, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_vanila_latte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_americano, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_cpn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_mocha, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_crml, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_tanggal)
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(40, 40, 40)
                        .addComponent(txt_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Totalharga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Totalharga1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Totalharga2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(131, 131, 131)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(lbl_tanggal))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nasgor)
                            .addComponent(txt_nasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caramel)
                            .addComponent(txt_crmel_late, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_crml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(migor)
                            .addComponent(txt_migor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_mg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(capucino)
                            .addComponent(txt_capucino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_cpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(soyam)
                            .addComponent(txt_soyam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_soto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cafemocha)
                            .addComponent(txt_cfe_mcha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txt_mocha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sokam)
                            .addComponent(txt_sokam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_sop_kmbg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vanilalatte)
                            .addComponent(txt_vnla_late, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_vanila_latte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nasi)
                            .addComponent(txt_nasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_rice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(americano)
                            .addComponent(txt_amrcano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_americano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txt_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(txt_kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(Totalharga)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Totalharga1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Totalharga2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nasgorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nasgorActionPerformed
        // TODO add your handling code here:
        int nasigoreng=12000;
        if (nasgor.isSelected()) {
            txt_nasgor.setText(""+nasgor.getText());
            txt_nasgor.setText(""+nasigoreng);
           
        }else{
            txt_nasgor.setText("");
        }
    }//GEN-LAST:event_nasgorActionPerformed

    private void migorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_migorActionPerformed
        // TODO add your handling code here:
        int miegoreng = 8000;
        if(migor.isSelected()){
            txt_migor.setText(""+migor.getText());
            txt_migor.setText(""+miegoreng);
           
        }else{
            txt_migor.setText("");
        }
    }//GEN-LAST:event_migorActionPerformed

    private void txt_soyamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_soyamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_soyamActionPerformed

    private void soyamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soyamActionPerformed
        // TODO add your handling code here:
        int sotoayam = 16000;
        if (soyam.isSelected()) {
            txt_soyam.setText(""+soyam.getText());
            txt_soyam.setText(""+sotoayam);
           
        }else{
            txt_soyam.setText("");
        }
    }//GEN-LAST:event_soyamActionPerformed

    private void sokamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sokamActionPerformed
        // TODO add your handling code here:
        int sopkambing = 15000;
        if (sokam.isSelected()) {
          txt_sokam.setText(""+sokam.getText());
          txt_sokam.setText(""+sopkambing);
        }else{
            txt_sokam.setText("");
        }
    }//GEN-LAST:event_sokamActionPerformed

    private void NasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NasiActionPerformed
        // TODO add your handling code here:
        int nasi = 5000;
        if (Nasi.isSelected()) {
            txt_nasi.setText(""+Nasi.getText());
            txt_nasi.setText(""+nasi);
        }else{
            txt_nasi.setText("");
        }
    }//GEN-LAST:event_NasiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int total = 0;
        int pesanan = 0;
        int satuan=0;
        if (nasgor.isSelected()) {
            String ng= txt_ng.getText();
            int jmlng=Integer.parseInt(ng);
            int hargang=jmlng*12000;
            total=total+hargang;
            pesanan=pesanan+jmlng;
            satuan=12000;
        } if(migor.isSelected()){
            String mg = txt_mg.getText();
            int jmlhmg=Integer.parseInt(mg);
            int hargamg=jmlhmg*8000;
            total=total+hargamg;
            pesanan=pesanan+jmlhmg;
            Totalharga.setText("jumlah pesanan nasi goreng = "+mg);
        } if(soyam.isSelected()){
            String soyam=txt_soto.getText();
            int jmlhsoyam=Integer.parseInt(soyam);
            int Hargasoyam=jmlhsoyam*16000;
            total=total+Hargasoyam;
            pesanan=pesanan+jmlhsoyam;
        } if(sokam.isSelected()){
            String sokam = txt_sop_kmbg.getText();
            int jmlhsokam=Integer.parseInt(sokam);
            int hargasokam=jmlhsokam*15000;
            total=total+hargasokam;
            pesanan=pesanan+jmlhsokam;
        } if(Nasi.isSelected()){
            String nasi = txt_rice.getText();
            int jmlhnasi=Integer.parseInt(nasi);
            int harganasi=jmlhnasi*5000;
            total=total+harganasi;
            pesanan=pesanan+jmlhnasi;
        }if(caramel.isSelected()){
            String caramell=txt_crml.getText();
            int jmlhcaramell=Integer.parseInt(caramell);
            int harga =jmlhcaramell*46000;
            total=total+harga;
            pesanan=pesanan+jmlhcaramell;
        }if(capucino.isSelected()){
            String capucinoo = txt_cpn.getText();
            int jmlhcapucino=Integer.parseInt(capucinoo);
            int hargacpn = jmlhcapucino*32000;
            total=total+hargacpn;
            pesanan=pesanan+jmlhcapucino;
        }if (cafemocha.isSelected()) {
            String cafemochaa = txt_mocha.getText();
            int jmlhcafemocha=Integer.parseInt(cafemochaa);
            int hargacafemocha = jmlhcafemocha*43000;
            total=total+hargacafemocha;
            pesanan=pesanan+jmlhcafemocha;
        }if (vanilalatte.isSelected()) {
            String vanilatte=txt_vanila_latte.getText();
            int jmlhvanilate=Integer.parseInt(vanilatte);
            int hargavanilate= jmlhvanilate*45000;
            total=total+hargavanilate;
            pesanan=pesanan+jmlhvanilate;
        }if (americano.isSelected()) {
            String americanoo=txt_americano.getText();
            int jmlhvanilatte=Integer.parseInt(americanoo);
            int hargaamericano=jmlhvanilatte* 26000;
            total=total+hargaamericano;
            pesanan=pesanan+jmlhvanilatte;
        }

        txt_harga.setText("RP  "+total+",-");
        Totalharga.setText("===Jumlah yang Dibayar Sebesar "+total+"===");
       Totalharga1.setText("          ==jumlah yang dipesan "+pesanan+"==");
    }//GEN-LAST:event_jButton1ActionPerformed
    private void txt_ngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ngActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ngActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       
        txt_ng.setText(null);
        txt_mg.setText(null);
        txt_soto.setText(null);
        txt_sop_kmbg.setText(null);
        txt_rice.setText(null);
        txt_crml.setText(null);
        txt_cpn.setText(null);
        txt_mocha.setText(null);
        txt_vanila_latte.setText(null);
        txt_americano.setText(null);
        txt_harga.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(null, "keluar pembayaran makanan","Exit",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (x==JOptionPane.YES_OPTION ) {
           dispose();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cafemochaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cafemochaActionPerformed
        // TODO add your handling code here:
        int caffemcha = 43000;
        if (cafemocha.isSelected()) {
            txt_cfe_mcha.setText(""+cafemocha.getText());
            txt_cfe_mcha.setText(""+caffemcha);
        }else{
            txt_cfe_mcha.setText("");
        }
    }//GEN-LAST:event_cafemochaActionPerformed

    private void txt_crmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_crmlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_crmlActionPerformed

    private void caramelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caramelActionPerformed
        // TODO add your handling code here:
        int cramellt = 46000;
        if (caramel.isSelected()) {
            txt_crmel_late.setText(""+caramel.getText());
            txt_crmel_late.setText(""+cramellt);
        }else{
            txt_crmel_late.setText("");
        }
    }//GEN-LAST:event_caramelActionPerformed

    private void capucinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capucinoActionPerformed
        // TODO add your handling code here:
        int capucinoo = 32000;
        if (capucino.isSelected()) {
            txt_capucino.setText(""+capucino.getText());
            txt_capucino.setText(""+capucinoo);
        }else{
            txt_capucino.setText("");
        }
    }//GEN-LAST:event_capucinoActionPerformed

    private void vanilalatteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vanilalatteActionPerformed
        // TODO add your handling code here:
        int vanila = 45000;
        if (vanilalatte.isSelected()) {
            txt_vnla_late.setText(""+vanilalatte.getText());
            txt_vnla_late.setText(""+vanila);
        }else{
            txt_vnla_late.setText("");
        }
    }//GEN-LAST:event_vanilalatteActionPerformed

    private void americanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_americanoActionPerformed
        // TODO add your handling code here:
        int americanoo =26000;
        if (americano.isSelected()) {
            txt_amrcano.setText(""+americano.getText());
            txt_amrcano.setText(""+americanoo);
        }else{
            txt_amrcano.setText("");
        }
    }//GEN-LAST:event_americanoActionPerformed

    private void txt_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hargaActionPerformed

    private void TotalhargaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TotalhargaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalhargaMouseClicked

    private void txt_sop_kmbgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sop_kmbgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sop_kmbgActionPerformed

    private void Totalharga1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Totalharga1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Totalharga1MouseClicked

    private void Totalharga2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Totalharga2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Totalharga2MouseClicked

    private void txt_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bayarActionPerformed
        // TODO add your handling code here:
        a=Integer.parseInt(txt_harga.getText());
        b=Integer.parseInt(txt_ng.getText());
        h=a-b;
        txt_harga.setText(""+h);
    }//GEN-LAST:event_txt_bayarActionPerformed

    private void txt_kembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kembalianActionPerformed

    private void btn_kembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembalianActionPerformed
        // TODO add your handling code here
        int duit = Integer.parseInt((txt_bayar.getText()));
        int kembali = duit - h;
        
        txt_kembalian.setText(""+kembali);
    }//GEN-LAST:event_btn_kembalianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ksir_penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ksir_penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ksir_penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ksir_penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ksir_penjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Nasi;
    private javax.swing.JLabel Totalharga;
    private javax.swing.JLabel Totalharga1;
    private javax.swing.JLabel Totalharga2;
    private javax.swing.JRadioButton americano;
    private javax.swing.JButton btn_kembalian;
    private javax.swing.JRadioButton cafemocha;
    private javax.swing.JRadioButton capucino;
    private javax.swing.JRadioButton caramel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_tanggal;
    private javax.swing.JRadioButton migor;
    private javax.swing.JRadioButton nasgor;
    private javax.swing.JRadioButton sokam;
    private javax.swing.JRadioButton soyam;
    private javax.swing.JTextField txt_americano;
    private javax.swing.JTextField txt_amrcano;
    private javax.swing.JTextField txt_bayar;
    private javax.swing.JTextField txt_capucino;
    private javax.swing.JTextField txt_cfe_mcha;
    private javax.swing.JTextField txt_cpn;
    private javax.swing.JTextField txt_crmel_late;
    private javax.swing.JTextField txt_crml;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_kembalian;
    private javax.swing.JTextField txt_mg;
    private javax.swing.JTextField txt_migor;
    private javax.swing.JTextField txt_mocha;
    private javax.swing.JTextField txt_nasgor;
    private javax.swing.JTextField txt_nasi;
    private javax.swing.JTextField txt_ng;
    private javax.swing.JTextField txt_rice;
    private javax.swing.JTextField txt_sokam;
    private javax.swing.JTextField txt_sop_kmbg;
    private javax.swing.JTextField txt_soto;
    private javax.swing.JTextField txt_soyam;
    private javax.swing.JTextField txt_vanila_latte;
    private javax.swing.JTextField txt_vnla_late;
    private javax.swing.JRadioButton vanilalatte;
    // End of variables declaration//GEN-END:variables
}
